// <auto-generated />
namespace SAAS_AIMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migrate6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrate6));
        
        string IMigrationMetadata.Id
        {
            get { return "201708271855312_migrate-6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
