// <auto-generated />
namespace AIMS.Data.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migrate34 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrate34));
        
        string IMigrationMetadata.Id
        {
            get { return "201709151536579_migrate-34"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
